//
//  ProgressBarDraw.swift
//  Progress-Bar
//
//  Created by AuthorName on 3/22/17.
//  Copyright © 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class ProgressBarDraw : NSObject {

    //// Drawing Methods

    public dynamic class func drawProgressBar(frame: CGRect = CGRect(x: 1, y: 0, width: 300, height: 16), progress: CGFloat = 111) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Progess Border Drawing
        let progessBorderPath = UIBezierPath(roundedRect: CGRect(x: frame.minX, y: frame.minY + 1, width: fastFloor((frame.width) * 0.99333 + 0.5), height: 14), cornerRadius: 7)
        UIColor.darkGray.setStroke()
        progessBorderPath.lineWidth = 2
        progessBorderPath.stroke()


        //// Progress Active Drawing
        let progressActivePath = UIBezierPath(roundedRect: CGRect(x: 2, y: 2, width: progress, height: 12), cornerRadius: 6)
        UIColor.lightGray.setFill()
        progressActivePath.fill()
    }

}
